// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(BackendDbContext))]
    [Migration("20220920140728_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Entities.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ActivityType")
                        .HasColumnType("integer");

                    b.Property<string>("AppBundleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ModelType")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("Backend.Entities.Building", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("ElectricityCarbonIntensity")
                        .HasColumnType("double precision");

                    b.Property<double>("ElectricityEnergySourcePercentage")
                        .HasColumnType("double precision");

                    b.Property<double?>("ExteriorGlazingAreaOverride")
                        .HasColumnType("double precision");

                    b.Property<double?>("ExteriorWallAreaOverride")
                        .HasColumnType("double precision");

                    b.Property<double>("ExteriorWallUValue")
                        .HasColumnType("double precision");

                    b.Property<double>("ExtractedExteriorGlazingArea")
                        .HasColumnType("double precision");

                    b.Property<double>("ExtractedExteriorWallArea")
                        .HasColumnType("double precision");

                    b.Property<double>("ExtractedFloorArea")
                        .HasColumnType("double precision");

                    b.Property<double?>("FloorAreaOverride")
                        .HasColumnType("double precision");

                    b.Property<double>("GlazingSolarHeatGainCoefficient")
                        .HasColumnType("double precision");

                    b.Property<double>("GlazingUValue")
                        .HasColumnType("double precision");

                    b.Property<double>("Height")
                        .HasColumnType("double precision");

                    b.Property<double>("InfiltrationRate")
                        .HasColumnType("double precision");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("NaturalGasCarbonIntensity")
                        .HasColumnType("double precision");

                    b.Property<double>("NaturalGasEnergySourcePercentage")
                        .HasColumnType("double precision");

                    b.Property<int>("NumberOfFloors")
                        .HasColumnType("integer");

                    b.Property<double>("OperationalEnergyUseIntensity")
                        .HasColumnType("double precision");

                    b.Property<double>("OtherEnergySourceCarbonIntensity")
                        .HasColumnType("double precision");

                    b.Property<double>("OtherEnergySourcePercentage")
                        .HasColumnType("double precision");

                    b.Property<string>("PrimaryBuildingType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProjectNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Buildings");
                });

            modelBuilder.Entity("Backend.Entities.ExtractionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastRun")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ExtractionLog");
                });

            modelBuilder.Entity("Backend.Entities.Model", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AutodeskHubId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AutodeskItemId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AutodeskProjectId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("BuildingId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RevitVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.ToTable("Models");
                });

            modelBuilder.Entity("Backend.Entities.Room", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<Guid?>("BuildingId")
                        .HasColumnType("uuid");

                    b.Property<double>("ExteriorWallArea")
                        .HasColumnType("double precision");

                    b.Property<double>("ExteriorWindowArea")
                        .HasColumnType("double precision");

                    b.Property<double>("FloorArea")
                        .HasColumnType("double precision");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("Backend.Entities.RoomType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("EquipmentPowerDensity")
                        .HasColumnType("double precision");

                    b.Property<double>("LightingPowerDensity")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("PeopleDensity")
                        .HasColumnType("double precision");

                    b.Property<double>("PeopleLatentRate")
                        .HasColumnType("double precision");

                    b.Property<double>("PeopleSensibleRate")
                        .HasColumnType("double precision");

                    b.Property<double>("VentilationRate")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("RoomTypes");
                });

            modelBuilder.Entity("Backend.Entities.RoomTypePercentage", b =>
                {
                    b.Property<Guid>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BuildingId")
                        .HasColumnType("uuid");

                    b.Property<double>("Percentage")
                        .HasColumnType("double precision");

                    b.Property<Guid>("RoomTypeId")
                        .HasColumnType("uuid");

                    b.HasKey("RoomId");

                    b.HasIndex("BuildingId");

                    b.ToTable("RoomTypePercentage");
                });

            modelBuilder.Entity("Backend.Entities.Model", b =>
                {
                    b.HasOne("Backend.Entities.Building", null)
                        .WithMany("Models")
                        .HasForeignKey("BuildingId");
                });

            modelBuilder.Entity("Backend.Entities.Room", b =>
                {
                    b.HasOne("Backend.Entities.Building", null)
                        .WithMany("Rooms")
                        .HasForeignKey("BuildingId");
                });

            modelBuilder.Entity("Backend.Entities.RoomTypePercentage", b =>
                {
                    b.HasOne("Backend.Entities.Building", null)
                        .WithMany("RoomTypePercentages")
                        .HasForeignKey("BuildingId");
                });

            modelBuilder.Entity("Backend.Entities.Building", b =>
                {
                    b.Navigation("Models");

                    b.Navigation("RoomTypePercentages");

                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
